### ISSUE TITLE
The keyboard does not have settings for keyboard lights in macOS 10.15.1

### ISSUE THREAD

**Issue by Jie2GG** [hieplpvip/AsusSMC#50]
In Mojave, you can see settings for keyboard lights in keyboard preferences, but these options disappear after upgrading to Catalina.

**Comment by hieplpvip** [comment]
Hi. On Catalina, native control of keyboard backlight is not available due to Apple rewrote their drivers for keyboard backlight. I haven't found a way to fix it, so I have to workaround by controlling backlight manually, which means some features available on Mojave and below (e.g. auto turn off, smooth transitions, settings,...) are not available on Catalina.
